USE SALAO


-- Carga Salão
CREATE OR ALTER PROCEDURE SP_OLTP_SALAO (@DATA_CARGA DATETIME)
AS
BEGIN

END


-- Carga Agendamento
CREATE OR ALTER PROCEDURE SP_OLTP_AGENDAMENTO (@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_AGENDAMENTO
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_AGENDAMENTO
	SELECT @DATA_CARGA, A.horario, A.status, A.idSalao
	FROM TB_AGENDAMENTO A
END


-- Carga Serviço
CREATE OR ALTER PROCEDURE SP_OLTP_SERVICO (@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_SERVICO
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_SERVICO
	SELECT @DATA_CARGA, A.horario, A.idSalao, S.idFuncionario, S.idTipoServico, T.VALOR
	FROM TB_SERVICO S JOIN TB_AGENDAMENTO A
	ON(S.idAgendamento = A.ID)
	JOIN TB_TIPO_SERVICO T
	ON(T.CODIGO = S.idTipoServico)
END


-- Carga Cliente
CREATE OR ALTER PROCEDURE SP_OLTP_CLIENTE (@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_CLIENTE
	WHERE @DATA_CARGA = DATA_CARGA

	INSERT INTO TB_AUX_CLIENTE
	SELECT @DATA_CARGA, C.id, C.nome, C.dt_nascimento, C.cidade
	FROM TB_CLIENTE C
END


-- Carga Tipo Serviço
CREATE OR ALTER PROCEDURE SP_OLTP_TIPO_SERVICO (@DATA_CARGA DATETIME)
AS
BEGIN

END


-- Carga Funcionário
CREATE OR ALTER PROCEDURE SP_OLTP_FUNCIONARIO (@DATA_CARGA DATETIME)
AS
BEGIN

END


-- Execução das Procedures

EXEC SP_OLTP_AGENDAMENTO '20240101'

EXEC SP_OLTP_CLIENTE '20240101'

EXEC SP_OLTP_FUNCIONARIO '20240101'

EXEC SP_OLTP_SALAO '20240101'

EXEC SP_OLTP_SERVICO '20240101'

EXEC SP_OLTP_TIPO_SERVICO '20240101'