-- CARGA DIM_SALAO
CREATE OR ALTER PROCEDURE SP_DIM_SALAO (@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @CODIGO_SALAO INT, @NOME_SALAO VARCHAR(100), @CIDADE VARCHAR(100), @UF VARCHAR(2)

	DECLARE C_SALAO CURSOR FOR SELECT CODIGO_SALAO, NOME_SALAO, CIDADE, UF
								   FROM TB_AUX_SALAO
								   WHERE @data_carga = DATA_CARGA

	OPEN C_SALAO

	FETCH C_SALAO INTO @CODIGO_SALAO, @NOME_SALAO, @CIDADE, @UF

	WHILE(@@FETCH_STATUS = 0)
	BEGIN	
		IF(EXISTS(SELECT * FROM DIM_SALAO WHERE @CODIGO_SALAO = COD_SALAO))
		BEGIN
			UPDATE DIM_SALAO
			SET NM_SALAO = @NOME_SALAO, CIDADE = @CIDADE, UF = @UF
			WHERE @CODIGO_SALAO = COD_SALAO
		END
		ELSE
		BEGIN
			INSERT INTO DIM_SALAO
			VALUES(@CODIGO_SALAO, @NOME_SALAO, @CIDADE, @UF)
		END

		FETCH C_SALAO INTO @CODIGO_SALAO, @NOME_SALAO, @CIDADE, @UF
	END
	CLOSE C_SALAO
	DEALLOCATE C_SALAO
END


-- CARGA DIM_FUNCIONARIO
CREATE OR ALTER PROCEDURE SP_DIM_FUNCIONARIO (@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @CODIGO_FUNCIONARIO INT, @NOME_FUNCIONARIO VARCHAR(100), @CPF VARCHAR(45), @TELEFONE VARCHAR(45)

	DECLARE C_FUNCIONARIO CURSOR FOR SELECT CODIGO_FUNCIONARIO, NOME_FUNCIONARIO, CPF, TELEFONE
								   FROM TB_AUX_FUNCIONARIO
								   WHERE @data_carga = DATA_CARGA

	OPEN C_FUNCIONARIO

	FETCH C_FUNCIONARIO INTO @CODIGO_FUNCIONARIO, @NOME_FUNCIONARIO, @CPF, @TELEFONE

	WHILE(@@FETCH_STATUS = 0)
	BEGIN	
		IF(EXISTS(SELECT * FROM DIM_FUNCIONARIO WHERE @CODIGO_FUNCIONARIO = COD_FUNCIONARIO))
		BEGIN
			UPDATE DIM_FUNCIONARIO
			SET NM_FUNCIONARIO = @NOME_FUNCIONARIO, CPF = @CPF, TELEFONE = @TELEFONE
			WHERE @CODIGO_FUNCIONARIO = COD_FUNCIONARIO
		END
		ELSE
		BEGIN
			INSERT INTO DIM_FUNCIONARIO
			VALUES(@CODIGO_FUNCIONARIO, @NOME_FUNCIONARIO, @CPF, @TELEFONE)
		END

		FETCH C_FUNCIONARIO INTO @CODIGO_FUNCIONARIO, @NOME_FUNCIONARIO, @CPF, @TELEFONE
	END
	CLOSE C_FUNCIONARIO
	DEALLOCATE C_FUNCIONARIO
END


-- CARGA DIM_TIPO_SERVICO
CREATE OR ALTER PROCEDURE SP_DIM_TIPO_SERVICO (@DATA_CARGA DATETIME)
AS
BEGIN

END


-- CARGA DIM_CLIENTE
CREATE OR ALTER PROCEDURE SP_DIM_CLIENTE (@DATA_CARGA DATETIME)
AS
BEGIN

END


-- CARGA FATO_AGENDAMENTO


-- CARGA FATO_SERVICO


-- CARGA DIM_TEMPO
CREATE OR ALTER PROCEDURE SP_DIM_TEMPO (@DT_INICIAL DATE, @DT_FINAL DATE)
AS
BEGIN
	SET LANGUAGE Brazilian
	
	DECLARE @INICIO DATE, @SEMESTRE VARCHAR(25), @SEMESTRE_INT INT, @TRIMESTRE VARCHAR(25), @FIM_SEMANA VARCHAR(3)

	DELETE FROM DIM_TEMPO
	WHERE DATA >= @DT_INICIAL AND DATA <= @DT_FINAL

	SET @INICIO = @DT_INICIAL

	WHILE(@DT_INICIAL <= @DT_FINAL)
	BEGIN

		--Calculo de Semestre
		IF (MONTH(@DT_INICIAL) <= 6)
		BEGIN
			SET @SEMESTRE = CONCAT('1º Semestre / ', YEAR(@DT_INICIAL))
			SET @SEMESTRE_INT = 1
		END
		ELSE
		BEGIN
			SET @SEMESTRE = CONCAT('2º Semestre / ', YEAR(@DT_INICIAL))
			SET @SEMESTRE_INT = 2
		END

		--Trimestre
		SET @TRIMESTRE = CONCAT(DATENAME(qq, @DT_INICIAL), '° Trimestre / ', YEAR(@DT_INICIAL))

		--Calculo Final de Semana
		IF (DATENAME(dw, @DT_INICIAL) = 'Sábado' or DATENAME(dw, @DT_INICIAL) = 'Domingo')
		BEGIN
			SET @FIM_SEMANA = 'SIM'
		END
		ELSE
		BEGIN
			SET @FIM_SEMANA = 'NAO'
		END

		--Inserção do Dia
		INSERT INTO DIM_TEMPO
		VALUES ('DIA', @DT_INICIAL, DATEPART(dd, @DT_INICIAL), DATENAME(dw, @DT_INICIAL), @FIM_SEMANA, NULL, 'NAO', DATEPART(mm, @DT_INICIAL), DATENAME(mm, @DT_INICIAL), DATENAME(qq, @DT_INICIAL), @TRIMESTRE, @SEMESTRE_INT, @SEMESTRE, YEAR(@DT_INICIAL)) 
		SET @DT_INICIAL = DATEADD(dd, 1, @DT_INICIAL)
	END

	--Inserção do Mês
	INSERT INTO DIM_TEMPO (NIVEL, MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO)
	SELECT DISTINCT 'MES', MES, NOME_MES, TRIMESTRE, NOME_TRIMESTRE, SEMESTRE, NOME_SEMESTRE, ANO
			FROM DIM_TEMPO
			WHERE DATA >= @INICIO AND DATA <= @DT_FINAL

	--Inserção do Ano
	INSERT INTO DIM_TEMPO (NIVEL, ANO)
	SELECT DISTINCT 'ANO', ANO
			FROM DIM_TEMPO
			WHERE DATA >= @INICIO AND DATA <= @DT_FINAL
END