CREATE DATABASE DATAWAREHOUSE
USE DATAWAREHOUSE

-- Salão
CREATE TABLE TB_SALAO(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_ESPECIALIZACAO INT,
	NOME VARCHAR(45) NOT NULL,
	CPF VARCHAR (15) NOT NULL UNIQUE,
	DTNASCIMENTO DATETIME NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	RUA VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	NUMERO VARCHAR(10)
)

-- Agendamento

-- Cliente

-- Funcionário
CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	CPF VARCHAR(45) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
	DTNASCIMENTO DATETIME NOT NULL,
	RUA VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL
)
-- Serviço

-- ServiçoProduto

-- Produto
CREATE TABLE TB_PRODUTO(
	CODIGO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	QUANTIDADE INT NOT NULL
)

--Especialização
CREATE TABLE TB_ESPECIALIZACAO(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
)

--Chaves estrangeiras

ALTER TABLE TB_FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_TO_ESPECIALIZACAO
FOREIGN KEY(ID_ESPECIALIZACAO) REFERENCES TB_ESPECIALIZACAO(ID)