CREATE DATABASE SALAO
USE SALAO

DROP TABLE TB_Servico
DROP TABLE TB_Agendamento
DROP TABLE TB_Cliente
DROP TABLE TB_SERVICO_TIPOSERVICO
DROP TABLE TB_TIPO_SERVICO
DROP TABLE TB_PRODUTO
DROP TABLE TB_SERVICO_PRODUTO
DROP TABLE TB_SALAO
DROP TABLE TB_FUNCIONARIO
DROP TABLE TB_ESPECIALIZACAO


-- Salão
CREATE TABLE TB_SALAO(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	CNPJ VARCHAR (18) NOT NULL UNIQUE,
	RUA VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	NUMERO VARCHAR(10) --retirar dps
)

-- Agendamento
CREATE TABLE TB_Agendamento (
    ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    horario DATETIME NOT NULL,
    status VARCHAR(11) NOT NULL CHECK(STATUS IN('AGENDADO', 'CANCELADO', 'TERMINADO')),
	VALOR_TOTAL FLOAT NOT NULL,
    idSalao INT NOT NULL,
    idCliente INT NOT NULL,
)

-- Cliente
CREATE TABLE TB_Cliente (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    cpf VARCHAR(45) NOT NULL UNIQUE,
	EMAIL VARCHAR(50),
	dt_nascimento DATE NOT NULL,
    telefone VARCHAR(45) NOT NULL,
	SEXO VARCHAR(15),
    rua VARCHAR(45) NOT NULL,
    cidade VARCHAR(45) NOT NULL,
    numero VARCHAR(10) 
)

-- Funcionário
CREATE TABLE TB_FUNCIONARIO(
	MATRICULA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	TELEFONE VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DTNASCIMENTO DATE NOT NULL,
	SALARIO FLOAT NOT NULL,
	DT_CONTRATACAO DATETIME NOT NULL,
	DT_DEMISSAO DATETIME,
	CIDADE VARCHAR(45) NOT NULL,
	RUA VARCHAR(45) NOT NULL,
	BAIRRO VARCHAR(45) NOT NULL,
	ID_ESPECIALIZACAO INT NOT NULL,
	ID_SALAO INT NOT NULL
)

-- Serviço
CREATE TABLE TB_Servico (
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    descricao VARCHAR(200),
	VALOR_SERVICO FLOAT NOT NULL,
    idFuncionario INT NOT NULL,
    idAgendamento INT NOT NULL,
)

-- Serviço_Produto
CREATE TABLE TB_SERVICO_PRODUTO (
    CODIGO_PRODUTO INT NOT NULL,
    ID_SERVICO INT NOT NULL,
	PRIMARY KEY(CODIGO_PRODUTO, ID_SERVICO)
)

-- TipoServiço
CREATE TABLE TB_TIPO_SERVICO(
	CODIGO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	SERVICO VARCHAR(45) NOT NULL,
	VALOR FLOAT NOT NULL,
)

-- TipoServico_Servico
CREATE TABLE TB_SERVICO_TIPOSERVICO(
	ID_SERVICO INT NOT NULL,
	ID_TIPO_SERVICO INT NOT NULL,
	PRIMARY KEY(ID_SERVICO, ID_TIPO_SERVICO)
)

-- Produto
CREATE TABLE TB_PRODUTO(
	CODIGO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR FLOAT NOT NULL
)

-- Especialização
CREATE TABLE TB_ESPECIALIZACAO(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(30) NOT NULL
)

-- Chaves estrangeiras

ALTER TABLE TB_agendamento
ADD CONSTRAINT FK_AGENDAMENTO_TO_SALAO
FOREIGN KEY (idSalao) REFERENCES TB_SALAO(id);

ALTER TABLE TB_agendamento
ADD CONSTRAINT FK_AGENDAMENTO_TO_CLIENTE
FOREIGN KEY (idCliente) REFERENCES TB_CLIENTE(id);

ALTER TABLE TB_Servico
ADD CONSTRAINT FK_SERVICO_TO_FUNCIONARIO
FOREIGN KEY (idFuncionario) REFERENCES TB_Funcionario(MATRICULA);

ALTER TABLE TB_Servico
ADD CONSTRAINT FK_SERVICO_TO_AGENDAMENTO
FOREIGN KEY (idAgendamento) REFERENCES TB_Agendamento(id);

ALTER TABLE TB_SERVICO_PRODUTO
ADD CONSTRAINT FK_SERVICOPRODUTO_TO_PRODUTO
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES TB_PRODUTO(CODIGO);

ALTER TABLE TB_SERVICO_PRODUTO
ADD CONSTRAINT FK_SERVICOPRODUTO_TO_SERVICO
FOREIGN KEY (ID_SERVICO) REFERENCES TB_SERVICO(ID);

ALTER TABLE TB_FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_TO_ESPECIALIZACAO
FOREIGN KEY(ID_ESPECIALIZACAO) REFERENCES TB_ESPECIALIZACAO(ID)

ALTER TABLE TB_FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO_TO_SALAO
FOREIGN KEY(ID_SALAO) REFERENCES TB_SALAO(ID)

ALTER TABLE TB_SERVICO_TIPOSERVICO
ADD CONSTRAINT FK_TIPOSERVICO_TO_SERVICO
FOREIGN KEY(ID_SERVICO) REFERENCES TB_SERVICO(ID)

ALTER TABLE TB_SERVICO_TIPOSERVICO
ADD CONSTRAINT FK_SERVICO_TIPOSERVICO_TO_TIPOSERVICO
FOREIGN KEY(ID_SERVICO) REFERENCES TB_TIPO_SERVICO(CODIGO)