USE SALAO

-- SALÃO
CREATE PROCEDURE SP_POPULAR_SALAO (@NOME VARCHAR(45), @CNPJ VARCHAR(15), @DTNASCIMENTO DATETIME, @TELEFONE VARCHAR(20), @RUA VARCHAR(45), @CIDADE VARCHAR(45), @NUMERO VARCHAR(10) OUTPUT)
AS
BEGIN
	INSERT INTO TB_SALAO
	VALUES(@NOME, @CNPJ, @DTNASCIMENTO, @TELEFONE, @RUA, @CIDADE, @NUMERO)
END

-- AGENDAMENTO
CREATE PROCEDURE SP_POPULAR_AGENDAMENTO (@HORARIO DATETIME, @STATUS VARCHAR(11), @ID_SALAO INT, @ID_CLIENTE INT OUTPUT)
AS
BEGIN
	INSERT INTO TB_Agendamento
	VALUES(@HORARIO, @STATUS, @ID_SALAO, @ID_CLIENTE)
END

-- CLIENTE


